---
- name: OpenVPN Client Keys | Generate client key
  command: openssl req -nodes -newkey rsa:4096 -keyout {{item}}.key -out {{item}}.csr -days 3650 -subj /CN=OpenVPN-Client-{{item}}/
    chdir=/etc/openvpn/keys
    creates={{item}}.key
  with_items: clients

- name: OpenVPN Client Keys | Sign client key
  command: openssl x509 -req -in {{item}}.csr -out {{item}}.crt -CA ca.crt -CAkey ca-key.pem -days 3650
    chdir=/etc/openvpn/keys
    creates={{item}}.crt
  with_items: clients

- name: OpenVPN Client Keys | Generate client config
  template: src=client.ovpn.j2 dest=/etc/openvpn/{{item}}-{{cname}}.ovpn owner=root group=root
  with_items: clients

- name: OpenVPN Client Keys | Fetch ca key
  fetch: src=/etc/openvpn/keys/ca.crt dest={{client_config_dest}}/{{item}}/{{cname}}/ca.crt flat=yes
  with_items: clients

- name: OpenVPN Client Keys | Fetch tls-auth key
  fetch: src=/etc/openvpn/keys/ta.key dest={{client_config_dest}}/{{item}}/{{cname}}/ta.key flat=yes
  with_items: clients
  when: openvpn_2fa_google == 'no'

- name: OpenVPN Client Keys | Fetch client key
  fetch: src=/etc/openvpn/keys/{{item}}.key dest={{client_config_dest}}/{{item}}/{{cname}}/{{item}}.key flat=yes
  with_items: clients

- name: OpenVPN Client Keys | Fetch client cert
  fetch: src=/etc/openvpn/keys/{{item}}.crt dest={{client_config_dest}}/{{item}}/{{cname}}/{{item}}.crt flat=yes
  with_items: clients

- name: OpenVPN Client Keys | Fetch client config
  fetch: src=/etc/openvpn/{{item}}-{{cname}}.ovpn dest={{client_config_dest}}/{{item}}/{{cname}}/{{cname}}.ovpn flat=yes
  with_items: clients
