---
# tasks file for openvpn

- name: install openvpn
  apt: name={{ item }} state=present
  with_items:
    - openvpn
    - easy-rsa
    - iptables-persistent

- name: Ensure group 'nogroup' is present
  group: name=nogroup state=present

- name: Setup 2fa
  include: setup_2fa.yml
  when: openvpn_2fa_google == 'yes'
  tags:
    - client_keys
    - server_keys

- name: Setup server keys
  include: server_keys.yml
  when: not openvpn_restore_keys
  tags:
    - server_keys

- name: Restore keys
  include: restore_keys.yml
  when: openvpn_restore_keys
  tags:
    - server_keys
    - client_keys

- name: copy openvpn config file
  template: src=server.conf.j2 dest=/etc/openvpn/{{openvpn_config_file}}.conf owner=root group=root
  notify:
    - restart openvpn

- name: enable ipv4 forwarding
  sysctl: name=net.ipv4.ip_forward value=1

- name: Add port rules (iptables)
  include: iptables.yml
  when: openvpn_iptables_enabled == 'yes'

- name: generate client configs
  include: client_keys.yml
  when: clients is defined and not openvpn_restore_keys
  tags:
    - client_keys

#- name: generate client configs
#  include: client_keys_2fa.yml
#  when: clients and openvpn_2fa_google == 'yes'
#  tags:
#    - client_keys

- name: setup openvpn auto-start (init-style) & start
  service: name={{openvpn_service_name}} enabled=yes state=started
