---
- name: enable openvpn
  service: name="{{openvpn_service_name}}" enabled=yes

- name: start openvpn
  service: name="{{openvpn_service_name}}" state=started

- name: restart openvpn
  service: name="{{openvpn_service_name}}" state=restarted